@extends('site.layouts.index')
@section('content')

<section class="privacy__sec">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="custom__heading">
					<h1>Privacy Policy</h1>
				</div>
				<div class="inner__privacy__content">
					<p>MED24 Technologies LLC. ("MED24," "We," "Us" or "Our") has developed this privacy policy ("Privacy Policy") for the benefit of the users ("You," "Your" and "Yourself") of its website and mobile apps, including https://www.MED24.ae (individually and collectively, the "Site"). This Privacy Policy summarizes how MED24 handles the personally identifying information that You voluntarily provide when You use the Site and that We may automatically collect when You visit the Site ("Personal Information").</p>
					<p><strong>If You are accessing, using or browsing this Site on behalf of an individual other than Yourself, which may be either a natural person or entity other than Yourself:</strong></p>
					<ul>
						<li>You represent, warrant and covenant that You are at least age 18:</li>
						<li>You represent, warrant and covenant that You are authorized to engage in the activities that You conduct within the Site on behalf of that person or entity other than Yourself, which by way of illustration but not limitation includes the submission and receipt of any and all Personal Information on behalf of that person or entity other than Yourself;</li>
						<li>You agree that We can rely on Your representation that You are authorized to engage in the activities that You conduct within the Site on behalf of that natural person or entity other than Yourself; and</li>
						<li>You understand that "You," "Your," and "Yourself" in this Privacy Policy mean both that natural person or entity and You acting on behalf of that natural person or entity other than Yourself.</li>
					</ul>
					<p>This Site is controlled and operated by MED24 from its offices within the United Arab Emirates. Accordingly, this Privacy Policy, and how MED24 handles the information that You voluntarily provide when You use the Site and information that We may automatically collect when You visit the Site, is governed by United Arab Emirates federal Laws and Dubai state laws, and not by the laws of any country, territory or jurisdiction other than the United Arab Emirates and Dubai specifically. We make no representation that the Site is appropriate or available for use outside of the United Arab Emirates. Those who choose to access the Site are responsible for compliance with applicable local laws and regulations.</p>
					<p>Your use of this Site will be deemed conclusively to constitute Your acceptance of and agreement to this Privacy Policy and all portions hereof. </p>
					<p>MED24 reserves the right, at its sole discretion, to change this Privacy Policy at any time. If We decide to change the Privacy Policy, We will post the changes in appropriate places on the Site so that You are aware of the changed Privacy Policy. Your continued use of the Site after the Effective Date for any such changes to the Privacy Policy will be deemed conclusively to constitute Your acceptance of and agreement to the changed Privacy Policy. Consequently, You should frequently review this Privacy Policy. </p>
					<h4>What Personal Information does MED24 collect?</h4>
					<p>MED24 collects several types of <strong>Personal Information</strong>. For example, to use some of its services and access certain areas of the Site, You must provide Personal Information that can be traced back to You, such as full name, Email address, mobile number, password & e-mail address for the purpose of signing up. Other optional information that can be added by the user is emirates ID, Insurance ID and medical records that would be used for sending prescriptions to Pharmacy where the emirates ID and insurance ID is mandatory. Also the medical records could be used for reference when at a healthcare provider visit. We collect this Personal Information that You voluntarily provide through the use of on-line data entry, survey and registration forms. MED24 gathers most of this Personal Information from You during an initial voluntary User registration process for the Site. MED24 also occasionally asks You for Personal Information at other times, including when You complete optional survey forms, fill out optional contact forms for additional information on particular products and services or use a particular service. </p>
					<p>To access and use MED24 request for booking <strong>("RFB")</strong> or schedule an appointment using MED24 On-Line Booking system <strong>("OBS")</strong> (individually and collectively referred to as the <strong>"Appointment Services"</strong>) to make an appointment with providers of healthcare services (collectively, "Healthcare Providers"), You must submit to Us the requested appointment information (the "Appointment Materials") during the completion of the Appointment Services scheduling process within the Site. This personally identifying information that You submit with the Appointment Materials can be traced back to You. MED24 treats all personally identifying information received from You with the Appointment Materials or created from Your use of the Appointment Services as Protected Health Information, regardless of whether an appointment is scheduled or a scheduled appointment is fulfilled. Personal Information that includes or is linked or associated with health-related information that You submit elsewhere on the Site without the Appointment Materials is not Protected Health Information and is not treated as such by MED24. </p>
					<p>When You visit the Site, MED24 may also automatically serve and collect data via or from <strong>Cookies</strong> and similar data collection technologies. A “Cookie” is a text file that a website sends to a visitor’s browser and is stored on Your computer, mobile phone, tablet, or other connected device (collectively, “Computer”). Cookies can store information about Your visit to and use of Our Site or other websites, can make that information available to Us or third parties, and can help Us offer You functionalities on Our Sites.</p>
					<p>We may use other similar technologies, including web beacons (also called “pixels,” “tags,” or “clear GIFs”) and JavaScript, to fulfill similar functions as Cookies. A web beacon is often a one-pixel, transparent image (although it can be a larger or visible image as well), located on a website or in an email or other type of message and retrieved from a website on the Internet. Similarly, our mobile application may integrate “software development kits” (SDKs) provided by Ourselves or third parties. Both web beacons and SDKs are used for similar purposes as Cookies, and are treated as “Cookies” for purposes of this Privacy Policy.</p>
					<p>When We place and access Cookies on Your Computer, these Cookies are known as “first-party” Cookies. Cookies may also be placed and accessed by third-party advertisers or Our third-party service providers; these are known as “third-party” Cookies. When third-party Cookies are used, third parties may receive information about Your visit to Our Site and use it to present content or advertisements to You on Our Sites, to recognize You and customize Your experience at third-party sites, or for any other purpose described in this Privacy Policy. Additionally, Cookies can either be “persistent” (i.e., they remain on Your Computer until You delete them) or temporary (i.e., they last only until You close Your browser). </p>
					<p>MED24 may also collect Personal Information about you from third parties, and we may combine information that is de-identified with Personal Information. We will treat the combined information as Personal Information as provided in this Privacy Policy.</p>
					<h4>What about the collection of Personal Information from children?</h4>
					<p>MED24 Sites are general audience sites intended for users 18 years of age and older. We do not knowingly collect personal information from persons under age of 18. Our site or mobile application allows users to add their family member’s details under the user’s account for ease of access. This information is added voluntarily by the user under his/her own discretion. </p>
					<h4>How does MED24 use the Personal Information we collect?</h4>
					<p>Med24 may use the Personal Information we obtain to:</p>
					<ul>
						<li>Provide products and services you request.</li>
						<li>Advertise our and our affiliates’ and customers’ products and services.</li>
						<li>Communicate with you about new information or features available through the Site or that MED23 otherwise feels might be of interest to users of the Site.</li>
						<li>Allow Med24 and our third-party advertisers and retailers and their affiliates to communicate with you to deliver relevant information or offers. </li>
						<li>Operate, maintain, and improve the Site.</li>
						<li>Make improvements to the Site to provide our users with a more personalized, relevant and intelligent service.</li>
						<li>Identify the interests and needs of the users of our Site. </li>
						<li>Operate, evaluate and improve our business (including developing new products and services; managing our communications; determining the effectiveness of our sales, marketing and advertising; analyzing and enhancing our products, services, websites and apps; ensuring the security of our networks and information systems; performing accounting, auditing, invoicing, reconciliation and collection activities; and improving and maintaining the quality of our customer service operations).</li>
						<li>Perform data analyses (including market and consumer search and analytics, trend analysis and profiling, financial analysis and de-identification or anonymization of personal information).</li>
						<li>Provide customer support and respond to and communicate with you about your requests, questions and comments.</li>
						<li>Protect against, identify and prevent fraud and other prohibited or illegal activity, claims and other liabilities.</li>
						<li>Comply with applicable legal requirements and our policies.</li>
						<li>Establish, exercise and defend legal claims.</li>
						<li>Monitor and report compliance issues.</li>
						<li>For systems administration and troubleshooting purposes for the Site.</li>
						<li>To report aggregate information to Our advertisers and others.</li>
					</ul>
					<p>In addition, we use clickstream data (data regarding usage of the Site, whether identifiable to users or de-identified) to determine usage patterns and how we may tailor our websites and apps to better meet the needs of our users. </p>
					<h4>What should You know about Cookies?</h4>
					<p>Refer to the cookies’ policy</p>
					<h4>Does MED24 disclose Your Personal Information to third parties?</h4>
					<p>MED24 may share Your Personal Information: (i) with third parties who have agreements with Us, including marketers, advertisers and other health service providers; (ii) if MED24 is required by law to do so, including laws outside Your country of residence; (iii) in the event of a transfer of ownership of MED24, merger or other similar transaction (including one in connection with any bankruptcy or similar proceedings); or (iv) as otherwise set forth in this Privacy Policy, including as set forth below. Note, however, that MED24 is not and cannot be responsible for the activities or privacy policies of any third party with whom Your Personal Information is shared.</p>
					<ul>
						<li>With respect to obtaining certain products and/or services from this Site, MED24 may disclose to a third party Your Personal Information that We gather from You during an initial voluntary User registration process for the Site ("Registration Information"); as a result, You do not have to enter Your Registration Information more than once. MED24 may also disclose Your Registration Information to certain third parties in connection with various programs and tools created and administered by third parties that are included in the Site as an additional service to users. </li>
						<li>We may provide Your Registration Information to Our marketing partners with whom You have explicitly authorized Us to share this information, and whose offers You have elected to receive via electronic delivery, telemarketing and direct mail. Additionally, We may employ other third parties to perform services or functions on Our behalf in order to improve Our Site, marketing and promotional efforts, communications or other services. Those third parties may include authorized contractors, consultants and other companies working with Us (collectively, "Agents"). These Agents only have access to Your Personal Information as needed to perform their functions, and they may not use any of Your Personal Information for any other purpose than providing or improving MED24' services and offerings.</li>
						<li>MED24 also reserves the right to share or transfer Your Registration Information or other Personal Information as We determine in Our sole discretion to be necessary or appropriate in the following circumstances: to comply with a legal requirement; to enforce Our terms and conditions; to protect Our operations or those of any affiliate of MED24; to protect Our rights, privacy, safety or property, or that of any affiliate of MED24, You or others; to disclose any activities or information about You to law enforcement or other government officials, including public or government authorities outside Your country of residence; in connection with an investigation of fraud, for the administration of justice, intellectual property infringements or other activity that is illegal or may expose Us or You to legal liability; in cooperation with various law enforcement inquiries; to allow Us to pursue available remedies or limit Our damages; and/or in emergency situations.</li>
						<li>MED24 discloses Personal Information to third parties or advertisers in aggregate form, that is, in a manner that cannot be traced back to You. For example, MED24 might tell an advertiser how many users performed a booking throughout a certain period of time.</li>
					</ul>
					<h4>How does MED24 use and disclose Your Personal Information?</h4>
					<p>When You use the Booking System Services to request an appointment with a selected Healthcare Provider, all personal information that You submit with the Appointment Materials or created from Your use of the booking system is used and disclosed by MED24 as per the agreement between MED24 and the healthcare provider. This means that MED24 may only use and disclose Your personal information on behalf of, or to provide services to, the Healthcare Provider for the booking system services available. </p>
					<p>For the use of prescription service, the personal information that will be shared with the pharmacy to ensure that your medicines can be dispensed are the emirates ID, Insurance ID, your full name, mobile number and the prescription details. This will be used to allow the pharmacist to dispense your medicines and get in touch with You for the delivery or collection of such medicines. </p>
					<h4>What does MED24 do to keep Your Personal Information and Protected Health Information Secure?</h4>
					<p>On this Site and within Med24, We seek to use appropriate administrative, technical and physical security measures that are designed to reasonably safeguard Your Personal Information and Protected Health Information under Our control.</p>
					<p>Please be advised, however, that although Med24 has endeavored to create a secure and reliable Site and mobile application for its users, the confidentiality and security of any communication or material transmitted to or from MED24 via this Site or e-mail cannot be guaranteed to be 100% secure at any time. When disclosing any Personal Information or Protected Health Information, You should remain mindful of the fact that it is potentially accessible to the public, and consequently, can be collected and used by others without Your consent. Accordingly, You should consider carefully if You want to submit sensitive information that You would not want disclosed to the public and should recognize that Your use of the Internet and this Site is solely at Your risk. You, alone, are ultimately responsible for maintaining the secrecy for all Your Personal Information including Your Protected Health Information. MED24 has no responsibility or liability to anyone for the security of Your Protected Health Information or any of Your Personal Information transmitted via the Internet. Med24 urges all of its users to be careful and responsible whenever they are on-line.</p>
					<p>Please be advised that MED24 could be using third party vendors or services to host your personal information or health information such as AWS (AMAZON WEB SERVCIES). We seek to use the appropriate security measures such as encryption to protect Your information. </p>
					<h4>Do You have the ability to access, change or remove Your Personal Information?</h4>
					<p>At any time, You may contact MED24 via e-mail to request: </p>
					<ul>
						<li>A summary of any of Your Personal Information retained by MED24; </li>
						<li>A change to the Your Personal Information maintained by MED24; or </li>
						<li>Removal of Your Personal Information from MED24' database.  </li>
					</ul>
					<p>You should send Your request to <a href="JavaScript:;">info@MED24.ae</a>. In the event MED24 receives such a request, MED24 may require You to confirm or verify any change to Your Personal Information to ensure that your information is secure and no unauthorized access takes place. If the request is repetitive and complex, we might request an administrative fee to extract the information. This extraction could take up to a month or more if the request is very complex. </p>
					<h4>Data Retention </h4>
					<p>We will only retain your personal data for as long as reasonably necessary to fulfil the purposes we collected it for, including for the purposes of satisfying any legal, regulatory, tax, accounting or reporting requirements. We may retain your personal data for a longer period in the event of a complaint or a legal hold.</p>
					<p>To determine the appropriate retention period for personal data, we consider the amount, nature and sensitivity of the personal data, the potential risk of harm from unauthorized use or disclosure of your personal data, the purposes for which we process your personal data and whether we can achieve those purposes through other means, and the applicable legal, regulatory, tax, accounting or other requirements.</p>
					<p>Generally, the retention periods for different aspects of your personal data will be six years.</p>
					<p>In some circumstances we will anonymize your personal data (so that it can no longer be associated with you) for research or statistical purposes, in which case we may use this information indefinitely without further notice to you</p>
					<h4>Contact Information</h4>
					<p>You may contact us with questions or concerns about our privacy policies or practices at:</p>
					<p><a href="mailto:info@med24.ae">info@med24.ae</a></p>
				</div>
			</div>
		</div>
	</div>
</section>

@endsection
{{-- @section('scripts')
@endsection --}}
